### PR TITLE
Added How To Play Page and Navbar

### PR DESCRIPTION
**Pull request by AnikateKoul**
I have added a Rules and FAQ's page. It consists of the basic rules to play the game.
It also consists of the general FAQ's regarding the game.
In addition to this, I have also added a Navbar to the website.
Thank You

### CODE REVIEW

**Comment by akshat-jn-crypto** [comment]
send screenshots

**Comment by AnikateKoul** [comment]
> send screenshots

Here you go
For the Home page : 
HomePage
For the How to Play Page : 
Rules
GeneralFAQ

**Comment by akshat-jn-crypto** [comment]
Pull for the same changes again

**Comment by akshat-jn-crypto** [comment]
Pull for the same changes again

**Comment by AnikateKoul** [comment]
> Pull for the same changes again

I didn't get you. Could you please clarify more.

**Pull request merged**
